### ISSUE TITLE
Categories, Genres, Tags

### ISSUE THREAD

**Issue by TheFusion21** [Revadike/UnofficialSteamWebAPI#6]
It would be hella awesome to create a map for Categories, Genres, Tags.
Ids, name (readable), value

Apparently category and genre is used by steam in some wierd interchangable way as some categories are also genres...
But should be able to map this regardless

**Comment by TheFusion21** [comment]
ok Tags is done XD
https://github.com/Revadike/InternalSteamWebAPI/wiki/Get-Store-Tags
This solved it already

**Comment by TheFusion21** [comment]
https://github.com/Revadike/InternalSteamWebAPI/wiki/Get-Store-Categories
And this for Categories

**Comment by Revadike** [comment]
Hmm, what can we do for genres?
