### ISSUE TITLE
Price history is no longer available

### ISSUE THREAD

**Issue by Leandro-C-Reis** [Revadike/UnofficialSteamWebAPI#7]
The link below is no longer available to list the price history, now you need to extract the prices from the html of the marketplace page.
[/market/pricehistory](https://github.com/Revadike/InternalSteamWebAPI/wiki/Get-Market-Price-History)

**Comment by Revadike** [comment]
https://steamcommunity.com/market/pricehistory/?appid=753&market_hash_name=228280-Xan works for me?

**Comment by Leandro-C-Reis** [comment]
Ok it's working now, yesterday the api was responding with status code 400.
