### ISSUE TITLE
steam api auth

### ISSUE THREAD

**Issue by gromaxbro** [Revadike/UnofficialSteamWebAPI#8]
i read your explanation about BeginAuthSessionViaCredentials its good but i dont understand 

```
mod = ses.get("https://api.steampowered.com/IAuthenticationService/GetPasswordRSAPublicKey/v1/?account_name=steamok1089937")
k1 = mod.json()["response"]["publickey_mod"]
k2 =  mod.json()["response"]["publickey_exp"]
t_2 = mod.json()["response"]["timestamp"]

print(k1)
print(mod.text)
t_1 = int(time())
public_key = rsa.PublicKey(int(k1, 16), int(k2, 2))


# encrypted_password = quote(b64encode(rsa.encrypt(password.encode(),rsa.PublicKey(int(k1,16), int(k2,2)))))
encrypted_pass = b64encode(rsa.encrypt(password.encode("utf-8"), public_key)).decode("utf-8")
```

i used this script to get encrypted pass
now 
![image](https://github.com/Revadike/InternalSteamWebAPI/assets/71826822/a45be783-b469-42d3-8e09-94ca94181a34)
added here but i dont know what to add in gurd data and language and device details 
when i run only with accountname and encryped pass it gives me
{"response":{"interval":5,"extended_error_message":""}}
every single time
what to do can you help me 
is somthing wrong in encryption?

**Comment by Revadike** [comment]
Wrong place to ask, this is the official API, we do the internal API

**Comment by gromaxbro** [comment]
but you were telling this 
https://stackoverflow.com/questions/74088647/how-to-get-steam-web-session-cookie-programatically
