### ISSUE TITLE
Finding Internal Api Calls

### ISSUE THREAD

**Issue by jakmaz** [Revadike/UnofficialSteamWebAPI#9]
Hello! 
I am developing an achievement tracker app. I also want it to fetch the best achievements guides. This is a page I am accessing.

[https://steamcommunity.com/app/1942280/guides/?searchText=&browsefilter=toprated&browsesort=creationorder&requiredtags%5B%5D=Achievements&requiredtags%5B%5D=English](https://steamcommunity.com/app/1942280/guides/?searchText=&browsefilter=toprated&browsesort=creationorder&requiredtags%5B%5D=Achievements&requiredtags%5B%5D=English)

However, when going to this website, in network tab I cannot see any API requests that response with JSON. How do you guys reverse-engineer it? I also tried mitmproxy but just can't find it

I know that at the end I can web scrape but since you are finding all of those, I believe that it is possible also there!

Likewise, I really appreciate any help!

**Comment by Revadike** [comment]
I don't think it exists

**Comment by jakmaz** [comment]
Yea, I got more understanding of the steam client server flow and found out that the first request returns all the guides in HTML already rendered on the server. It is not the case with some other things where we can see the exact request being made on the client side to fetch additional data

**Comment by jakmaz** [comment]
Yea, I got more understanding of the steam client server flow and found out that the first request returns all the guides in HTML already rendered on the server. It is not the case with some other things where we can see the exact request being made on the client side to fetch additional data

**Comment by MalikAQayum** [comment]
you need to use the documented web api.

https://api.steampowered.com/IPublishedFileService/QueryFiles/v1/?key=&format=json&query_type=0&&filetype=10&page=1&numperpage=100&appid=1942280&match_all_tags=0&include_recent_votes_only=0&totalonly=0&return_vote_data=1&return_tags=0&return_kv_tags=0&return_previews=0&return_children=0&return_short_description=0&return_for_sale_data=0&return_metadata=1
